{% set name = "transformers-embedder" %}
{% set data = load_setup_py_data() %}

package:
  name: "{{ name|lower }}"
  version: "{{ TRANSFORMERS_EMBEDDER_VERSION }}"

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}

requirements:
  build:
    - python
  run:
    - python

source:
  path: ../../

build:
  noarch: python
